
#define IMU_ACCEL_I2C 	0x3A // 0b00111010
#define IMU_GYRO_I2C_ADDRESS	0xD7

/* IMU ACCEL REGISTERS ADRESSES*/
#define IMU_ACCEL_WHOAMI 		0x0F

#define IMU_ACCEL_ADDR_CTRL0			0x1F
#define IMU_ACCEL_ADDR_CTRL1			0x20
#define IMU_ACCEL_ADDR_CTRL2			0x21
#define IMU_ACCEL_ADDR_CTRL3			0x22
#define IMU_ACCEL_ADDR_CTRL4			0x23
#define IMU_ACCEL_ADDR_CTRL5			0x24
#define IMU_ACCEL_ADDR_CTRL6			0x25
#define IMU_ACCEL_ADDR_CTRL7			0x26

#define IMU_ACCEL_ADDR_OUT_X_L_A		0x28
#define IMU_ACCEL_ADDR_OUT_X_H_A		0x29
#define IMU_ACCEL_ADDR_OUT_Y_L_A		0x2A
#define IMU_ACCEL_ADDR_OUT_Y_H_A		0x2B
#define IMU_ACCEL_ADDR_OUT_Z_L_A		0x2C
#define IMU_ACCEL_ADDR_OUT_Z_H_A		0x2D

/* IMU ACCEL REGISTERS CONFIG VALUE*/

#define IMU_ACCEL_CTRL1			0b01010111 //AODR: 0101 BDU: 0 AZEN=AYEN=AXEN: 1


/* IMU GYRO REGISTERS*/
#define IMU_GYRO_WHOAMI 		0x0F
